# Generated by Django 5.2.16 on 2026-07-14 04:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=50)),
                ('api_instance', models.CharField(max_length=20)),
                ('board_identifier', models.CharField(max_length=255)),
                ('careers_url', models.URLField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('last_import_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_type', 'api_instance', 'board_identifier'), name='jobs_employer_source_identity_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('source_job_id', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=1000)),
                ('application_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=255)),
                ('location_text', models.TextField(blank=True)),
                ('description_text', models.TextField(blank=True)),
                ('description_html_raw', models.TextField(blank=True)),
                ('content_completeness', models.CharField(choices=[('FULL', 'Full'), ('PARTIAL', 'Partial'), ('SNIPPET', 'Snippet'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('years_required_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('years_required_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('years_preferred', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience_requirement_type', models.CharField(blank=True, choices=[('REQUIRED', 'Required'), ('PREFERRED', 'Preferred'), ('NICE_TO_HAVE', 'Nice to have'), ('FLEXIBLE', 'Flexible'), ('AMBIGUOUS', 'Ambiguous'), ('NOT_FOUND', 'Not found')], max_length=20, null=True)),
                ('remote_canada_eligibility', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNCLEAR', 'Unclear')], max_length=10, null=True)),
                ('remote_countries', models.JSONField(blank=True, null=True)),
                ('workplace_type', models.CharField(blank=True, max_length=50, null=True)),
                ('office_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('office_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_km_from_origin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('career_track', models.CharField(blank=True, max_length=100, null=True)),
                ('role_family', models.CharField(blank=True, max_length=100, null=True)),
                ('match_band', models.CharField(blank=True, choices=[('MATCH', 'Match'), ('POSSIBLE', 'Possible'), ('STRETCH', 'Stretch'), ('NOT_A_MATCH', 'Not a match'), ('UNCLEAR', 'Unclear')], max_length=20, null=True)),
                ('classifier_version', models.CharField(blank=True, max_length=100, null=True)),
                ('classification_explanation', models.TextField(blank=True, null=True)),
                ('classification_evidence', models.JSONField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('raw_payload_hash', models.CharField(blank=True, max_length=64)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.employersource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_job_id'), name='jobs_job_source_identity_uniq'), models.CheckConstraint(condition=models.Q(('source_job_id', ''), _negated=True), name='jobs_job_source_job_id_not_blank')],
            },
        ),
    ]
